version: '3.8'

services:
  api-gateway:
    image: kdman/api-gateway:latest  # Docker Hub 이미지
    container_name: api-gateway
    depends_on:
      - user-service
      - public-data-service
      # - chat-service
      - board-service
    ports:
      - '3000:3000'
    networks:
      - default
    env_file:
      - .env
    environment:
      - USER_HOST=user-service
      - BOARD_HOST=board-service
      - PUBLIC_DATA_HOST=public-data-service
      - CHAT_HOST=chat-service
      - GATEWAY_PORT=${GATEWAY_PORT}
      - BOARD_PORT=${BOARD_PORT}
      - CHAT_PORT=${CHAT_PORT}
      - USER_PORT=${USER_PORT}
      - PUBLIC_DATA_PORT=${PUBLIC_DATA_PORT}
      - CHAT_GATEWAY_PORT=${CHAT_GATEWAY_PORT}
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USERNAME}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MONGO_HOST=${MONGO_HOST}
      - MONGO_PORT=${MONGO_PORT}
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_CHAT_URI=${MONGO_CHAT_URI}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
      - GITHUB_CALLBACK_URL=${GITHUB_CALLBACK_URL}
      - JWT_SECRET=${JWT_SECRET}
      - CLIENT_MAIN_URL=${CLIENT_MAIN_URL}
      - CLIENT_SIGNUP_URL=${CLIENT_SIGNUP_URL}
    restart: 'unless-stopped'

  user-service:
    image: kdman/user-service:latest
    container_name: user-service
    networks:
      - default
    env_file:
      - .env
    environment:
      - USER_HOST=user-service
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USERNAME}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    restart: 'unless-stopped'

  public-data-service:
    image: kdman/public-data-service:latest
    container_name: public-data-service
    networks:
      - default
    env_file:
      - .env
    environment:
      - PUBLIC_DATA_HOST=public-data-service
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USERNAME}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    restart: 'unless-stopped'

  
  board-service:
    image: kdman/board-service:latest
    container_name: board-service
    networks:
      - default
    env_file:
      - .env
    environment:
      - BOARD_HOST=board-service
      - BOARD_PORT=${BOARD_PORT}
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USERNAME}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    restart: 'unless-stopped'

networks:
  default:
    driver: bridge
chat-service:
    image: kdman/chat-service:latest
    container_name: chat-service
    networks:
      - default
    env_file:
      - .env
    environment:
      - CHAT_HOST=chat-service
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USERNAME}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MONGO_HOST=${MONGO_HOST}
      - MONGO_PORT=${MONGO_PORT}
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGO_URI=${MONGO_URI}
      - MONGO_CHAT_URI=${MONGO_CHAT_URI}
    restart: 'unless-stopped'
