name : CD Pipeline

on:
  workflow_run:
    workflows: ["Docker Image CI"]
    types:
      - completed

jobs:

  deploy:
    name: Deploy
    runs-on: ubuntu-20.04
    env:
      DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
      DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
    
    steps:
      - name: excuting remote ssh commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.AWS_SSH_HOST}}
          username: ${{secrets.AWS_USERNAME}}
          key: ${{secrets.AWS_SSH_KEY}}
          port: ${{secrets.AWS_SSH_PORT}}
          script_stop: true
          script: |
            cd ./actions-runner/compose
            sudo docker compose down
            sudo docker pull kdman/user-service:latest
            sudo docker pull kdman/public-data-service:latest            
            sudo docker pull kdman/board-service:latest
            sudo docker pull kdman/api-gateway:latest
            sudo docker rm -f user-service || true
            sudo docker rm -f public-data-service || true
            sudo docker rm -f board-service || true
            sudo docker rm -f api-gateway || true
            sudo docker compose -p down grabbme-be
            sudo docker compose -f ./docker-compose.yml up --remove-orphans -d

